name = "dodik"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "2052d9e1b5494957aa98602ad27ed692"

routes = [
  { pattern = "dodik.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.dodik.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.dodik.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.dodik.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.dodik.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.dodik.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.dodik.dpdns.org", custom_domain = true },
]

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/abidodik/abetnih/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/abidodik/abetnih/refs/heads/master/web/sub.html"
